# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    SMTP_USERNAME: ENC[AES256_GCM,data:uNRC1inNIS5hQ9Ijc9j4,iv:imvzOIttUAcxkv9IZgE+PLDMqSV8bHiNdK/v56oZlOQ=,tag:7x1liIYdPMB+Fq+NVid+2w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:e6eIEz//Ibk27rpPP5z114Ga4H50Aw==,iv:uneo6cPGpoi20sAvQyEyJaWogjNQwc3xGDWJqZNgkNw=,tag:TGuAGK1SmSgBnWTOc4C6NQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmllVnVNWkZHdWdUYlhm
            SzRYL1RKN2lCQjhaSHFnb2NsR25wR0E4YVc0Cnhmak9hRG9PVW1IY1ZSaVA0MGFs
            Njh6VXRuQ0VORWhaajRvUW9IS3Z4MVUKLS0tIFRJSGVzU3BhRzM2OEdsSEZ3d3oz
            L1YvdTdaWHdpa2JRdndEdlU2V2V0RVkK8cZqMOlFytj66G/uPHVahAKB0SLEiwnR
            lZmlOOuMoeth8gO7JBZdCnvNrdcA1xcwwXrKSt+4qHwcBbT6VJyucg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T12:28:53Z"
    mac: ENC[AES256_GCM,data:VfwtrBvJfEC6lGiAYObqmfRZ3F+zv38lbZISTcEQBdVFHK27pBQXtRd76ZgPrx5fJiz3wb38RvGxx8ATirG/BZSoQ8TJd1qqwgJD7cu22ArB71ctiSB9BcwqPdzfU7AtPw1enD+QKCsHaHVziR2Yek0DKJjB3Pl7pM39568CUps=,iv:xETgIV0ry9S9HCFU8FY08PS2Lct5kk8QOWUqpa9FXPw=,tag:FCANZJsiwaN6EfZ7uk1miw==,type:str]
    version: 3.13.3
