# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
stringData:
    SMTP_USERNAME: ENC[AES256_GCM,data:vN0NiEqgtmLVjqcFq+Z18Zksl7jXP4av,iv:zpkzpR9StN2mBVEdOPSqpUzVVsLeoQ/pVQzBR5MSy7A=,tag:NkVsEULOiJRaabkXMck/ug==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:6XE0dEdZosqQNZSyvEtMyaeXXk0VHvQ+2n+z5dEHcdwS8N2OdiHwYKtPUEJISTreJd37tTvTddw7TNLXctj3h0BeVVPWOigOK39ZLVnfryXwo8YGtfNVX5Rx,iv:3kPEm0pLFqh/+PWqpifq19oGvXtKhbpxmK7SfXhoju8=,tag:aA7LPM+HI3PclKCfepY1Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmllVnVNWkZHdWdUYlhm
            SzRYL1RKN2lCQjhaSHFnb2NsR25wR0E4YVc0Cnhmak9hRG9PVW1IY1ZSaVA0MGFs
            Njh6VXRuQ0VORWhaajRvUW9IS3Z4MVUKLS0tIFRJSGVzU3BhRzM2OEdsSEZ3d3oz
            L1YvdTdaWHdpa2JRdndEdlU2V2V0RVkK8cZqMOlFytj66G/uPHVahAKB0SLEiwnR
            lZmlOOuMoeth8gO7JBZdCnvNrdcA1xcwwXrKSt+4qHwcBbT6VJyucg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T00:41:27Z"
    mac: ENC[AES256_GCM,data:V1FUNJzEq1enwZy1f5T+K1Ixva7lVgN+BjiTh0x5uC3GSZlKutNo3rU8SDKx5INjiHbGb1v4TNTkv+242iMh4ZJK1s1cDwJ5lKBISKBuPlVwqkKTRqHZYkmJlzXiEhvXI7HeMWXasyAnuk35lZy6Q+LX/7Hr4hRFu71QyU/87MY=,iv:tT+g4kC0iaj0jUK49HWmX1qPKCt58CvXxLbdJ4FUecw=,tag:fCqQhsBxCL6JO34qWvJoPQ==,type:str]
    version: 3.13.3
