apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
