# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: wireguard-secret
    namespace: vpn
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:tSVFLoUFQMzG/lJ+lpyOTHiolU+hfyGcPzcY8Pr1eVbbZBl+rSKIhvZB9ew=,iv:Km4xg1dm8CU+SPGZwGshRerlog0acaqKKMRulka/LbI=,tag:QvKmTIdZ2YzyQ9k9m0C2TA==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:s6AuUmt0KOIrXoINN2YPjXSxo1ozTIGwOyxcEcKr4Ukw1DxA6sp/n0M8K/Q=,iv:FV4G55cgUaO/B/IoFjESpZcK1DZST4Zj6XPSRBorkgk=,tag:Kjo2JVHEn66ThMVFoipbVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V2pqdHE2eFQvZ0x1RmRY
              QnE5amZjcGZieWJOU2VYbzd3NjNuWUJVcVc0CnNxTzVNeThDS052MCtQQzk2cE9z
              OXZ3UTlKVU41cTE0WXhIT3ZxVktuQVUKLS0tIEFDMnRKRmdneUp2blkwNkNOakpI
              YVJ3RDBUSy8ydlYzenlnSklDSG5FSEkKcW20fRVuVdfo7iRqFLUakpCfGjYpnV+r
              c739TvP7CUXdzSjaSIHP3KAx8OklhLyBy+qnMXLiU8bV9pWRXGneCw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-04T19:36:38Z"
    mac: ENC[AES256_GCM,data:lhLkkxHgigVBL+adSMm+O6BaBRGlke4rSG6Seu+Mej9qeIEJsY0hdZ0CKrjpr5hJA8RUjAW9gbsac1oV3go9UOPrgX/6+BF+JC4RIp5TwAczUX+a1Cv13QGEPXm2LlZKvrOo9krzViQjcdATxVA3Fz0wFir39cSeDbZpXR6uW5c=,iv:ptdOhdaejJ8k0bGt3q1AyTiBdwG4XYfC64dxHdd/I8c=,tag:O24Z8ri8wzyNfbUqW3PzOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
