apiVersion: v1
kind: Secret
metadata:
    name: wireguard-secret
    namespace: vpn
stringData:
    server.conf: ENC[AES256_GCM,data:lLwxeA8RDhrb3lp8BMSgC0EizODfEzHPUsZxd1vYuFC+3+wPiY0U93cr+ARqP7AlJkftX78XeBNMQkF2iqeT8FXXoLU+g++CvJopjEQUPgG3Lpf6AOyo384A28HrtygnYHfvNlJ3cJfYTJBnQkwYDCcgA66cjYQjG5u+srBb+TT075nE6furkwztFxqmH1ORCaimdTOBDD1y9RUwGhg6SYF0Z7VVXaWeXaAw7gYoE2+nmyg9cvld7HzCjMNRkJCYMfAC0eNcx6QLP7/ZEjIC6KH0HiwdnCSWjwUmSeVxNaqlKZBpuGAr4r01Xa2NYuKKiQCcmHD5V0V72rx/n03dWkdpFPv9YkwPwtEX0FTVE+46PVJScC8FsHQ2nmLfj5hQ/8EDQS5sO9VlJoPMP9y7opXfsRDCpOAXWppz9bs175nPkYSH0xnhQmqBlc76S8tTnzwV91s8cCsEy+NvaogkdF9JCFSWP2d2xToImecAZ4fZHJyR+PIr40Axw/RTehMeBzs+PTHQ3+XGGYDE5zm6mlhFF5wRJqcA35fInQrXbPWcvsjTebfK9UCF1VjmJ138r/UEGWF4J2sNTP7UFzM5fcwT625slQe4W80JfW9io97OsofUeHHrWCzhzxo7tKdtFxc09M5tOnU9Tcy/QgB3Pr+C2aKAuh+mhRhdLXWF5CQeMwoGN+QPQlMqfP8a0zGdIkQlT2KgWj9scYR5TPBSDPYJguactM+Ya4BBhO9JUoXEL1SFLOINOpSZlJtuZBKeQ272Jh3AM5WKzkj5p2rbh/H1Po2BsMffk6x8+FTSMqipq2YQ64736ONCmB9d2XIE7Ha3nQ==,iv:p7uJRB3LvtgCyY6UUVW+izqzKeUQMOuU3o+5kbvFNJ4=,tag:7SE7zF8dOOvOvUyOYVLEYg==,type:str]
    startup.sh: ENC[AES256_GCM,data:m2eLltKiOxk8ioo1Hw0uAjpwErMyVRkDnuZ+YfWGVv6Js7rxovITjYmgWnI/tHoOjoik6s5XdGUx7iYEwuWPMXSxBgitoZl/rnmU4hv5B3JG6w3fMwFQuU7jUdqFhzn98v8kAyUlbbX7gGE+uBBMc8yKigNX7DQVnPl221avsgs9vFs4tUkSXCMYR1HkE0Mi7wM/fZw3DZTuwdq7VhX/fRVsn/plHlHk,iv:rWq0agkwhJrt4fo2DkQ3V0Wgf1Vl1JwFbL7uOAugfO8=,tag:165WtC1UtrGr12wx2UgsLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaEhEZUpFdkg2a2FYR0Yw
            aWQ4S2Y1eVJvQzRLRFA3RXozNjRVVTFCcUdrCnozUGJNZU1CbmZPcVkzUXRJM2tS
            ZVBOQUdOTDdPSmtnWm5ySjRVUHl2eFkKLS0tIHk4RmRmbUlDWnhDeWMveTdUUC9y
            c24wQ3F1UG9YNXBmdEg2cEhyTk1td0EK4/Tfsh8uKWNKLVL506dztMhwnULQONG2
            OQCHdOTVQ8x82MWWP0ObCM6WCrp4ufnCah1md2HmpJrvEyGn3x8DtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T16:54:35Z"
    mac: ENC[AES256_GCM,data:+wmQKrUan0A09SaHJkkjxeZszgNZGwg5OUB6dRHoUGm++tx5pJwGXhLvMWuaOOgwdfDoS26kKFCiRUAkBpEXSVDP2EPPZyRJPMpBmbb5PChvaWWOIXVO0t6nZiEkAHjvLlvovAt4nf6sHrWNvHAhIk24dE0M5hQei3arJIcNAFI=,iv:lOl6W0QTvksenlr08+IyLWG/ZF0wApDeeqOeDDsQowc=,tag:HrVX7Jy+HLFgdZYmWHHxDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
