apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard
  namespace: vpn
data:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Madrid
  PEERS: "2"
  SERVERURL: vpn.${SECRET_DOMAIN}
  SERVERPORT: "51820"
  PEERDNS: "192.168.1.121"
  # ALLOWEDIPS: "0.0.0.0/0, ::/0"
  # INTERNAL_SUBNET: "10.13.13.0"
