apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard
  namespace: vpn
data:
  PUID: "1000"
  PGID: "1000"
  TZ: Europe/Madrid
  SERVERURL: vpn.${SECRET_DOMAIN}
  PEERS: "5"
  PEERDNS: auto
  INTERNAL_SUBNET: 10.13.13.0
  # ALLOWEDIPS: 0.0.0.0/0
  # LOG_CONFS true
