apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  values:
    kubeletDir: /var/lib/kubelet
