apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.68.101
  share: /volume1/K8s-homelab
reclaimPolicy: Retain
volumeBindingMode: Immediate
