apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-server
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      initContainers:
        - name: volume-permission-fixes
          image: busybox:latest
          command: ["sh", "-c", "chown -R 1000:1000 /config /data"]
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: data
              mountPath: /data
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:1.5.3
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: media-config
          ports:
            - name: http
              containerPort: 6767
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: bazarr-config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: bazarr-config
          persistentVolumeClaim:
            claimName: bazarr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: media-data-pvc
