---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 300Mi
