---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: heimdall
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 2
    image:
      repository: linuxserver/heimdall
      tag: 2.4.13
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Madrid
      PUID: "1000"
      PGID: "1000"
    service:
      main:
        ports:
          http:
            port: 80
          https:
            port: 443
    persistence:
      config:
        enabled: true
        existingClaim: heimdall-config
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
