---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: heimdall
      version: 8.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 2
    image:
      repository: linuxserver/heimdall
      tag: 2.2.2
      pullPolicy: IfNotPresent
    env:
      TZ: Europe/Madrid
      PUID: "1000"
      PGID: "1000"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        external-dns/is-public: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
      hosts:
        - host: "heimdall.${SECRET_DOMAIN}"
          paths:
            - "/"
      tls:
        - secretName: heimdall-tls
          hosts:
            - "heimdall.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: heimdall-config
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
