apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: life-os
  namespace: life-os
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "life-os.${SECRET_DOMAIN}"
      secretName: life-os-tls
  rules:
    - host: "life-os.${SECRET_DOMAIN}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: life-os-app
                port:
                  number: 80
