apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.sops.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
