# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: life-os-secrets
    namespace: life-os
type: Opaque
stringData:
    #ENC[AES256_GCM,data:NlEsfts+BbYkp8UoAuy/FqDRAScPuwY780OBtb5yPq8MHbKZ,iv:BVSn1yHNQBfVpD6x37M1n4NDpjlADjA/24g8oNcsRh8=,tag:fdDoWAqhswtCaVSxqfmbNw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:F4QRzGk0VVCNOmfQsuzszg==,iv:hbkBY5U6JetlPlQMtC1axKrviJ2fhwihMKlOUBfbXAc=,tag:YdhgsjfnvD5Rhc66Huogog==,type:str]
    #ENC[AES256_GCM,data:FRBdSuJm32eFMPl5jYxtqmIY8rrv39Y9c2K6qPk7nkbFGZkrJA2I9rHZVrXL79QF6AmGglX5,iv:ylHEvelOsor2yIvQPyqnuXHpih3NL+NbX0iSlPrkbJE=,tag:a3L8+kdbXMpMeWOPkPgyDg==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:JUSeAQc/CQw2kaXYUniP4DBUgL/NZASxdjZtVBULdU+rNJJk8y70KOkGN7XuybDEY65HxzioP12ilD+2m9d9rttDHXezTfO2FFtAHYIKUCjkCjKZ5ENW+8z6dAdJtS+M//CElSxX0Wc7/tpR3bo=,iv:/Z44uXBZRXM6SvEMeyQC1R5F7hsWSi6Jibg6MzMEpc4=,tag:/TQ9bacO1Um0LsdRXZVj+Q==,type:str]
    #ENC[AES256_GCM,data:kaayUKECprgmOSwSpcW+46sHeGOSOwc2BFT3wAQR7FepFazmUxLyguel9Ce7RqZlUepaE8Y4dSsA,iv:WqMt43X/bkzBIbcYe3SbGwO3wdgLUq3mJEz8Qtq1UNc=,tag:RDNjnUXanrKrGjkCrZzwaw==,type:comment]
    API_SECRET_KEY: ENC[AES256_GCM,data:W/MYZmGGjhpvgEWkIPPhANwdkvIaSM+uQu/ZNgoC6HE=,iv:SNJNteeskzdLc2nsP/SMrQMerX2Ceh6HABerOMTgo60=,tag:Sn70Q5sH1MiNlm4u7Mn/YQ==,type:str]
    #ENC[AES256_GCM,data:joT+v88MQjUFZYTHCd6b68FeBjhqC5FwXhA98DSmdF7xQ8dmiOCCPWMbzWLj+VE4h6ejh/rYgSsbJ/9Td+dgKwxtZpoKFcGF77k=,iv:+cZwvKi+C5fZY0lcLqg6m6NsXnYNVVwwbR4pCZoiUYw=,tag:4ZhvmcPWJUypWub4sYWwaQ==,type:comment]
    GEMINI_API_KEY: ENC[AES256_GCM,data:jPpoBwC4IRpMdjBkwdj1v3SshuRJdFGhntavG5TmWrTwMkx18QwqcsxhPs/+apz+cE6GCK8=,iv:Enn9rOorbO7ioaOmN+ajZho1iFDs6iPqDMtzih8i/yA=,tag:QI69yJEbvff2RZ6vAuT2yQ==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENAI_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidHg5bXA5TmtsR3JMZzcr
            WXIxN1NqNjh2Z3ZHaDIzUXFzcjBvRk9aVENrCnNBSDN1dWQxMXRNN2c2OGtKaWIz
            aERqamgzSUR3aGNrWjZ1TWN6NmpPVmcKLS0tIHg1U25rczBIZnJ5RmtpZURVd245
            UzdhTlNwT05xMC9ZUTNneDgxb1NVZEUKYBci43eE2qkA1lMA4MxVOrYLbJ4Zdn+t
            yAIUEvOgzU3klO21DVxGkrLcHMId8ZRDLwR2bw+a7mfLjX+F2z4W3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T02:31:05Z"
    mac: ENC[AES256_GCM,data:UNd6UcdICjU3/IxV0V6Om+RJzfp4DD9dlS8U3U1qIDgVbBXqx9fU6rbNpbEVPadBtPSFaG/x358Cm4q58Q10Wrek2Ko2hPwOGODJdTMKNJKa+5gCOJ40cU8r64/B6lqgSP4HVjhlLNMEzU4AgxDk9rUlZNqFSSk6R/zyXJIdXgk=,iv:55b7BpUlXcovbk15BDRN4G/dlj154dZrkMqrBGlWemk=,tag:SSidD7+t7evOKRh2nDMWYw==,type:str]
    version: 3.13.3
