apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerun-web-html-pvc
  namespace: drive
  labels:
    service: filerun-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
