apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerun-web-userfiles-pvc
  namespace: drive
  labels:
    service: filerun-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-large
  resources:
    requests:
      storage: 800Gi
