---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw
resources:
  - namespace.yaml
  - secret.yaml
  - service-ai-server.yaml
  - ingress-ai-server.yaml
  - echo
  - kubepilot
  - domobot
  # - chronos
  # - apex

images:
  - name: ghcr.io/openclaw/openclaw
    newTag: 2026.5.20
