---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-home-pvc
  namespace: openclaw
  labels:
    app: openclaw
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
