apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:abj8qzRkMZotK/VU7Ond2SSYgQE9NueW8AD7x5k83cK7IAMmkVYRlPrHYVX6p/KIOgKY+ENyhTTWbmAxuZDDJQ==,iv:quESqTzj5/lFQ6ZnTDnuyAtUIel4gwNQJDaQPT7pJiE=,tag:M9qlA3EkB4P+42u/NhVXaw==,type:str]
    OLLAMA_API_KEY: ENC[AES256_GCM,data:D7Y+gkAfMAq/UMri,iv:GYFoM96OYlm2cLotLXTG9+vbn3ZbPcGRdY/7wME/rrY=,tag:jfTliK2YNMnIm5r+SSRfSQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:R3ej/TLTV4sE894s+xZvFJvq3fHC/vRVrf4tcvdXdIRR8BunlCkc,iv:/DZSux3lP1hjnUqn72u/vAZgqf40FxW9kLF0gAgqrrE=,tag:rC/y8hq0otoeTqIhlRIS4A==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENROUTER_API_KEY: ""
    TELEGRAM_BOT_TOKEN_ECHO: ENC[AES256_GCM,data:eW0wHN4KzO1Uhw1r8QTUhVe96TWLBqVuqFiF1PuCI28hGwYeIwX8GoVKTnZ3+g==,iv:vsqQTNuaZh3J5xKkECS5zkras9guIoTU6fXF/B0dPNg=,tag:fj5stxGIDBH9TMp16liJ6w==,type:str]
    TELEGRAM_BOT_TOKEN_KUBEPILOT: ENC[AES256_GCM,data:iP5mFrO9OihP3ipdblcP49+Tj9jaXY8QQQ+76tTrRhcUXs7Xamw8rIObKWmGsw==,iv:3uJCcOqAR96+qR+Adoat1KOhs5fvF0PEgTJGpDax3ts=,tag:sh8+WaBE8hDBowxFTJwmiA==,type:str]
    TELEGRAM_BOT_TOKEN_DOMOBOT: ENC[AES256_GCM,data:kD4oFiUPq09ccfSis13HCOAWykiZChuZIZEVsNNOppzYWXaC7x8P2EAl2wqXfg==,iv:XvRxlvuXJUPkHAxZ2FKcRVDGSXH8Xg9lnxO/OGlq8Bk=,tag:z6Dpg/mXXShyHwkkc85hfA==,type:str]
    TELEGRAM_BOT_TOKEN_CHRONOS: ENC[AES256_GCM,data:0A3sGPv466p94uXgga/yG/T8allnWTCv8OTL+K7+9cbXEYOJ2AiXHXYaKnU2Vg==,iv:0LNK+bD3aJZ513kD5AsViSRpAUhZ4TceyQ5eTWRmQPI=,tag:mDyL1D6FHQo+7FRkW/qfvA==,type:str]
    TELEGRAM_BOT_TOKEN_APEX: ENC[AES256_GCM,data:ogiqCXCMqCW3UcQyVF6BdldxJkDFgeWcd4P3O5o+tOLVR8gJM3PVFOEvJDOatw==,iv:CuFGllBnqnQa7Pom3XQvtjO7jiQ5Xx1R+m+6oKC5Dhk=,tag:PKoSL3BN1CDySsjcp384Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR2NWSU9YdGYvaE9OMmpP
            ZUg5WEpGV3hJSHBUZjdoWGx3TzE1RkpLUXhjCjlhYmFDUU9vd0hSbGRNZXhNc1Ir
            d1BnZGhOMzBZR1pRK0xPMng3ajF2Rm8KLS0tIEpVRmhBZ1o5T2IzL0ZOWjRPWk4r
            K0lZbWUrM1pNSFh1ZmgyUjNOT2JuVkEKeZxOdK522l29jyaeEDNB3M6P3t7/hIb7
            /vO02PM0aSymbGiLa3dimbt+nga9WIsXzf1szhMyAv0nnS3H21nJ3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T03:40:29Z"
    mac: ENC[AES256_GCM,data:F0HmEA1+yRL2hbJIEsvQY4FEgz++h/7jaEgZfP2fS0wyfBDsELot3M+ebbfwdwFqyegY307mJyWKdiE1YAWTEyUKAzbvc0K2NVHY1pZdO9h+xN4+HcZyTLV5Lp16gUBRLkvs4/urOJKvicSJRfAWWnsUvmjwNiFuZg7V7dJmQ/U=,iv:1jCro6agJoia+xagQhDcvefRyZALqvbjySuz3OktSik=,tag:6/tYSGId7ZpuDmNTrpqjfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
