apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:abj8qzRkMZotK/VU7Ond2SSYgQE9NueW8AD7x5k83cK7IAMmkVYRlPrHYVX6p/KIOgKY+ENyhTTWbmAxuZDDJQ==,iv:quESqTzj5/lFQ6ZnTDnuyAtUIel4gwNQJDaQPT7pJiE=,tag:M9qlA3EkB4P+42u/NhVXaw==,type:str]
    OPENCLAW_MODEL: ENC[AES256_GCM,data:XltsDmYMfJsgUQ==,iv:ye8068beNaQ1VXP4ryYWxY1iUXYavl14mJDUbfjJA+0=,tag:VJMNb19AQfeS5ZrJlgNRWw==,type:str]
    OPENAI_API_BASE: ENC[AES256_GCM,data:O4AGE3i1afJGrqRt40l4fd+z+PkjV97ej+x+GzwU0g==,iv:u0CU+S88Z+TTV557sJcWdbGxDD3oWlZfZbAScViJdgA=,tag:0apfjHm6dOlSd520Axwo0Q==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:neDHkciZ,iv:Sc1hDWAitoPyjDuc9f6jv2vEOZ2CZipAOvwbsWJvIAk=,tag:fDxQEuDulFfrCMvkxwocwg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:R3ej/TLTV4sE894s+xZvFJvq3fHC/vRVrf4tcvdXdIRR8BunlCkc,iv:/DZSux3lP1hjnUqn72u/vAZgqf40FxW9kLF0gAgqrrE=,tag:rC/y8hq0otoeTqIhlRIS4A==,type:str]
    ANTHROPIC_API_KEY: ""
    OPENROUTER_API_KEY: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR2NWSU9YdGYvaE9OMmpP
            ZUg5WEpGV3hJSHBUZjdoWGx3TzE1RkpLUXhjCjlhYmFDUU9vd0hSbGRNZXhNc1Ir
            d1BnZGhOMzBZR1pRK0xPMng3ajF2Rm8KLS0tIEpVRmhBZ1o5T2IzL0ZOWjRPWk4r
            K0lZbWUrM1pNSFh1ZmgyUjNOT2JuVkEKeZxOdK522l29jyaeEDNB3M6P3t7/hIb7
            /vO02PM0aSymbGiLa3dimbt+nga9WIsXzf1szhMyAv0nnS3H21nJ3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T03:02:11Z"
    mac: ENC[AES256_GCM,data:4Fw9uh5bv7qZlfhGU6dNKLMUM+iIwAnK03JuvtGs0I00VSpIxGXF9FOXMGJ2TPnKyWatYOAWTX3zs9MlYtwzLZajIKuGQLmwDeyfjhTKutvAMYyQ0zyGlEYR0V/E6Wii1TVSqoTy5OZ3SiP11owT1DePywDswmrjsOx+8rM8k6c=,iv:nYbNTPStPlcsdA6d7G0fPFCZeVfnZk/Uqj6ZIxUTL8s=,tag:/WmPchz54lYR2yoijFrAYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
