# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:0sjODkPz+I7wAy7pThLNKA==,iv:j6/1XFzvRv0+EMfRbquMR3toRuKEsBbGqamexHJrCQw=,tag:GltLumqGNyzM74gU4QnaWQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:+o9hD0Gh6UPldl2mnbcY4svevsCerTopdEFoDzCUuaBidxFSzQ==,iv:HPbLYtkFaKiR2CUNHJMRkdGWJcUeWS1N0oM3noW43co=,tag:FXHUXygf221bPcPkBsGQxg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:S2Ywbi9HHEloQz6AHbcsuhk=,iv:KaWM//5gH6vs+fGpCUZg9VUfJVOGEpm+sR2m3HaO1Mg=,tag:iNF/7tmhGpz+yU2pBGgqTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeDIvT2V3aWlkU3EweG00
            UHdxUUR0Uk9OKy9vZVR6MmxORFZpQWNJTEFNClFybUF5MjRCNEY2YXBNbWcrS3lO
            bHAwcUpVWS82NENxVE1ZNEpUNGo5cWsKLS0tIFdlQmlkWEZwOVh1ckFSL3N4MER2
            eS9aYkRZTExiOEM2bGgwSXdDTFVxVGMKCMY4qpbRcF8o7cpse0ah/dtxM5nFjz5l
            6XREEmqrDsvg0kQujEy07pKH0yt6heNhR2JtQgFiLDdocbPhs1a5YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T12:37:02Z"
    mac: ENC[AES256_GCM,data:cQwCES2/0YEVK8KmMIbqnayahHR+gjX+UtZ0zyIcPDXHNjeQ6nOK8ffK0Ywtp+Sws93Telf5UJc7huDuZwS5dSh/mIRGPwqoB37pJssd5RRLXstAng8bVgO1a0KIkDaZycVZJBV/LhLEavSTI+GvH6JcgxcyhT3eRSKUCbUpn9c=,iv:dRk07WGLzPbtf+EWpvjMMun6YD1AOsExudEUetm9Lmo=,tag:iMh2xwGLSp2LZaMn9x4Izg==,type:str]
    version: 3.13.3
