apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-home
  namespace: networking
data:
  AdGuardHome.yaml: |
    users:
      - name: alekssro
        password: $2a$12$NEFRYj/k.MjYSPG3svvQ4O9efojUwu37p6pQnZ6WOZSXVq0Txz9xG
      - name: heimdall
        password: $2a$12$wCJySysX10iBFo5VV9CWOOkzPuKZCBRMPRuu3sd00zy23dqieAYsq
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: en
    dns:
      bind_hosts:
      - 0.0.0.0
      port: 53
      statistics_interval: 7
      querylog_enabled: true
      querylog_file_enabled: true
      querylog_interval: 1
      querylog_size_memory: 1000
      anonymize_client_ip: false
      protection_enabled: true
      blocking_mode: default
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_response_ttl: 10
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      ratelimit: 20
      ratelimit_whitelist: []
      refuse_any: true
      upstream_dns:
      - https://dns.cloudflare.com/dns-query
      - https://dns.quad9.net/dns-query
      - "[/${SECRET_DOMAIN}/]192.168.68.20"
      - "[/vpn.${SECRET_DOMAIN}/]https://dns.cloudflare.com/dns-query"
      upstream_dns_file: ""
      bootstrap_dns:
      - 1.1.1.1
      - 9.9.9.9
      - 149.112.112.10
      - 2620:fe::10
      - 2620:fe::fe:10
      all_servers: false
      fastest_addr: false
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts: []
      cache_size: 4194304
      cache_ttl_min: 3600
      cache_ttl_max: 86400
      bogus_nxdomain: []
      aaaa_disabled: false
      enable_dnssec: true
      edns_client_subnet:
        custom_ip: ""
        enabled: false
        use_custom: false
      max_goroutines: 300
      ipset: []
      filtering_enabled: true
      filters_update_interval: 24
      parental_enabled: false
      rewrites: []
      safesearch_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      blocked_services: []
      local_domain_name: lan
      resolve_clients: false
      local_ptr_upstreams: []
    tls:
      enabled: false
      server_name: ""
      force_https: false
      port_https: 443
      port_dns_over_tls: 853
      port_dns_over_quic: 784
      port_dnscrypt: 0
      dnscrypt_config_file: ""
      allow_unencrypted_doh: false
      strict_sni_check: false
      certificate_chain: ""
      private_key: ""
      certificate_path: ""
      private_key_path: ""
    filters:
    - enabled: true
      url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      name: AdGuard DNS filter
      id: 1
    - enabled: true
      url: https://adaway.org/hosts.txt
      name: AdAway
      id: 2
    - enabled: true
      url: https://abp.oisd.nl
      name: oisd full
      id: 3
    whitelist_filters: []
    user_rules: []
    dhcp:
      enabled: false
      interface_name: "eth0"
      dhcpv4:
        gateway_ip: "192.168.68.1"
        subnet_mask: "255.255.255.0"
        range_start: "192.168.68.50"
        range_end: "192.168.68.250"
        lease_duration: 86400
        icmp_timeout_msec: 1000
        options: []
      dhcpv6:
        range_start: ""
        lease_duration: 86400
        ra_slaac_only: false
        ra_allow_slaac: false
    clients:
      runtime_sources:
        whois: true
        arp: true
        rdns: false
        dhcp: true
        hosts: true
      persistent: []
    log:
      enabled: true
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
      verbose: false
    schema_version: 33
