apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-logs
  namespace: networking
  labels:
    service: adguard-home
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
