apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home
  namespace: networking
  labels:
    service: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
