---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: networking
  labels:
    service: adguard-home
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      service: adguard-home
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: adguard-home
      labels:
        service: adguard-home
    spec:
      nodeSelector:
        kubernetes.io/hostname: nuc7pjyhn
      hostNetwork: true
      initContainers:
        - name: copy-configmap
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "mkdir -p /opt/adguardhome/conf && cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml"
          volumeMounts:
            - name: adguard-home-configmap
              mountPath: /tmp
            - name: adguard-home-config
              mountPath: /opt/adguardhome/conf
          securityContext:
            runAsUser: 0
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.23
          env:
            - name: TZ
              value: "Europe/Madrid"
          args:
            - "-c"
            - "/opt/adguardhome/conf/AdGuardHome.yaml"
            - "--work-dir"
            - "/opt/adguardhome/work"
            - "--no-check-update"
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 853
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
          volumeMounts:
            - name: adguard-home-config
              mountPath: /opt/adguardhome/conf
            - name: adguard-home-logs
              mountPath: /opt/adguardhome/work
      volumes:
        - name: adguard-home-configmap
          configMap:
            name: adguard-home
            items:
              - key: AdGuardHome.yaml
                path: AdGuardHome.yaml

        - name: adguard-home-config
          persistentVolumeClaim:
            claimName: adguard-home

        - name: adguard-home-logs
          persistentVolumeClaim:
            claimName: adguard-home-logs
