---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: 2.14.4
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: nextcloud
      tag: 24.0.1-apache
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
        hosts:
          - host: "nextcloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "nextcloud.${SECRET_DOMAIN}"
            secretName: "nextcloud-tls"
    nextcloud:
      host: nextcloud.${SECRET_DOMAIN}
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: username
        passwordKey: password
        tokenKey: serverinfo_token
      defaultConfigs:
        .htaccess: true
        apache-pretty-urls.config.php: true
        apcu.config.php: true
        apps.config.php: true
        autoconfig.php: false
        redis.config.php: false
        smtp.config.php: true
      configs:
        custom.config.php: |-
          <?php
          $CONFIG = array (
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://nextcloud.${SECRET_DOMAIN}',
            'filelocking.enabled' => 'true',
            'loglevel' => '2',
            'enable_previews' => true,
            'trusted_domains' =>
                [
                  'nextcloud',
                  'nextcloud.${SECRET_DOMAIN}'
                ]
          );
        redis.config.php: |-
          <?php
          $CONFIG = array (
            'memcache.local' => '\\OC\\Memcache\\Redis',
            'memcache.distributed' => '\OC\Memcache\Redis',
            'memcache.locking' => '\OC\Memcache\Redis',
            'redis' => array(
              'host' => getenv('REDIS_HOST'),
              'port' => getenv('REDIS_HOST_PORT') ?: 6379,
              'password' => getenv('REDIS_HOST_PASSWORD')
            )
          );
    internalDatabase:
      enabled: false
    mariadb:
      db:
        name: nextcloud
        password: db-password
        user: nextcloud
      enabled: true
      master:
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 8Gi
      replication:
        enabled: false
      rootUser:
        password: root-db-password
        forcePassword: true
    postgresql:
      enabled: false
    redis:
      enabled: true
      password: "redis-password"
      usePassword: true
    metrics:
      enabled: true
    cronjob:
      annotations: {}
      curlInsecure: false
      enabled: true
      failedJobsHistoryLimit: 5
      image: {}
      schedule: "*/5 * * * *"
      successfulJobsHistoryLimit: 2
    persistence:
      enabled: true
      existingClaim: nextcloud-config
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data
    podAnnotations:
      configmap.reloader.stakater.com/reload: "nextcloud-settings"
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        memory: 2Gi
