# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: nextcloud
stringData:
    username: ENC[AES256_GCM,data:Eo4tJzY7fqg=,iv:GyGWCoxKjqlt194nbBpg8S/0BPoTw0A74xh/ykFDmbw=,tag:MU8u5zfZjPyEE/oUZ4eV/A==,type:str]
    password: ENC[AES256_GCM,data:PGcPgC7cxbl3b6iQU46OrYMzAW98esbL+ocIZOp5NK0=,iv:7IIRMtUQnEC5E9rbKlbeoKX4Ruzo3L/QgaZCynKYOQ0=,tag:TdjJb+J2FQLbpt7UPoSHOw==,type:str]
    serverinfo_token: ENC[AES256_GCM,data:t+3tbFFBRkYSsLhV43lXzYBxD1/4AOrkwD5AchCHxfVJN8HDjnKQjSP7s9IunVSn,iv:/y9p5pyBPZ++azuMvWQb7bkiORKWFKHjR/Em/Xg/wec=,tag:H22AxCIrMP4quwlMTxgrJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1d2gyaDc1Y0VrR2tsaC8w
            OHZoWFc2TG1KYnhlV2V1Vk5IK3VTa3FPeEdFCkR6WFEwcnBwSGJuNmtLaDc3REg1
            UTExS0ZLV0ovWXgrb1h2eVpkWGFqYncKLS0tIHFSUVhlT1U5cGQ5VFBWYS9Da25a
            dE9yRG5QcnZCMjZzVG1VTEg1dCtjY0kKL89oXlvE9T/jo4DU1ZKizUKl+tbnmQ6w
            VY2FkA2caAyMPkMg2GitGrvDOg9iEyY/jFDDDZQ1hoEruPAqpzMuPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T19:10:26Z"
    mac: ENC[AES256_GCM,data:0AoZfY9GergN7nKCj9lzmiUFCuqeb4IFRd2GOMyEeAZ5FvZC/SbQIuKFId25w1d0w3kx35L9+RYR1rrLVAnJOoow8rlOWQeDXKgtpDD7GrhksPfPavd0Uspq5G1Vf90lvX0WJlBih9CBChnZoVb8jB0ycsrLD4PrTqLHzYt5f8k=,iv:+icjvnxfKVxVDRdW9fViCEp9aOWy89jGmmh87RiNHbM=,tag:Eew7IjtwtzZZcKvawYhp8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
