apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerun-db-pvc
  namespace: filerun
  labels:
    service: filerun-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
