apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerun-web-html-pvc
  namespace: filerun
  labels:
    service: filerun-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
