apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerun-web-userfiles-pvc
  namespace: filerun
  labels:
    service: filerun-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
