apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filerun-web-userfiles-pvc
  namespace: filerun
  labels:
    service: filerun-web
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
