apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: media-server
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: flaresolverr/flaresolverr:v3.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8191
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              memory: "256Mi"
