---
apiVersion: batch/v1
kind: Job
metadata:
  name: krr
  namespace: monitoring
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      serviceAccountName: krr
      restartPolicy: Never
      containers:
        - name: krr
          image: robustadev/krr:v1.29.0
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - python krr.py simple -p http://prometheus-service.monitoring.svc.cluster.local:9090 --max-workers 3 --width 2048
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi
