# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Smwjk4zgSCLBIK5jQ26e,iv:dRh2BdYiEzqKj9lpO0vMf0d2SpqTpVZfvfKUIVEEbDk=,tag:mD6Sy/xcVczOs3bgqS2W8g==,type:str]
    api-key: ENC[AES256_GCM,data:SAGdC3zLsuBdEvIUKunG1oZVi0uf9MtR3omqXyjQcLUgBXsptA==,iv:5XGiqT9sHvY0yt0NgQZ8QRF5I0sOyknRXZOlGXWGlH8=,tag:8qXxEVCB752OH7p/yUKc5g==,type:str]
sops:
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDRyV1BEQ3oraVlOenkv
            RnQ2L2ZYeGRrMGtReWF3eXJwejJWWCtWVFNJCjBXTk9HRi9wWTAwQmREbXZZNUNJ
            NnF1Z09KUDhNK0ZkSDJTWmp6V2JLb0EKLS0tIDB2bkxSaERRTm4zZGZLLzdHWkow
            TzhHUFVTWjlmT1pUMGIza1J4eHVpd2cK0L4GUYiRSX+nDxbBclfekDUWaYzdBpLJ
            wtWTPDqsextiyUBYgI7UpjGke3C/boqjIEt9Bx1QAvKR88iDHUEp4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T18:15:23Z"
    mac: ENC[AES256_GCM,data:y3fOOX0OwNPtMiGNd0s2V4eQkcW3e2BmgHKcihaaxh58eUNA3bRyj7wg+ACxl+qFM1MAa6fVAxxhOS6ps791rv90kUJC1IO+ElUGttwr503KWroWgkzHs+Xg2hXBp8rrKFqqW/LdoBaVOZ3DeM2UeVe7Y2Rrnidz7bZwp4EzGZQ=,iv:xM6iX1Atkh9TdG+bnap8P82SkwwMo+cFpkJHSCVcAE4=,tag:CYT+BUf0hhTXL5mdu/6rFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
