---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml
  - deploy.yaml
  - secret.sops.yaml
