---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-config-pvc
  namespace: owncloud
  labels:
    service: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-data-pvc
  namespace: owncloud
  labels:
    service: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
