---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-config-pvc
  namespace: owncloud
  labels:
    service: owncloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-data-pvc
  namespace: owncloud
  labels:
    service: owncloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 800Gi
