---
apiVersion: v1
kind: Service
metadata:
  name: owncloud-web
  namespace: owncloud
  labels:
    service: owncloud-web
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 9200
  selector:
    service: owncloud-web
