---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:1.23.16
          env:
            - name: UPTIME_KUMA_PORT
              value: "3001"
            - name: PORT
              value: "3001"
          ports:
            - name: uptime-kuma
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "448Mi"
            limits:
              memory: "448Mi"
          livenessProbe:
            exec:
              command:
                - node
                - extra/healthcheck.js
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 30
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data
      nodeSelector:
        kubernetes.io/hostname: nuc7pjyhn-rookie

      volumes:
        - name: kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
