# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: robusta-secrets
    namespace: monitoring
stringData:
    SIGNING_KEY: ENC[AES256_GCM,data:UXtts6+Bi9Ns2wugnHVNLZM/rgAeoKxVZirMvbh87sXcVfXt,iv:/88kIaFtQzJtvaxVcFuIQSt9gm6zQr0yQH8sHONbXe4=,tag:mCIucIh/n8VI2PXodGD7lw==,type:str]
    ROBUSTA_UI_TOKEN: ENC[AES256_GCM,data:sEF2krVYAd7GtNsGR671qAc5LyLk0KyWW0mKx1S1SqVQgCSC6kmQAaDU8mymaXJFIQnJw9Kw1XlIbPnO+JzyaoGmU0+nsrMtfAFOU21Z6gU3yONrLTnRZEmSYLtnyhCx0me2TPBnfrWoumiK+QZxpw2AldW8uDPxxHwzQvFsD1wFxqEaH/1vc04Yynn2qhSOOoSo45mOjMThmqNQLQ4sav56gpsPwsTWlBOR0cJsHz4TS5b8agXGISZxbQ9WKzXJcrHpgq2wUB/1+MxsFIrBUu6tZhtXH0SbH0ZK7rtSfhEaD/u2aQPbzV24oATDwGZ9PXI1NbMZhHDBAbIMVI3OOB+HiY0Ww51qTGbRev6N6NgGL93cNGus3MWvT4ZmHvIhlDv7l8sKtpedOze4XLezBBLTMYGKMvw8synytyxpB6GmoOnXXf/hOYDlxFYkRBoq9VH0u8+UPG/LtfJeScfStyOCKECuwlnINCf8yig6PoSYQ1tZNFBYFrxpmq7ZB8Xg4OjBwzlQonTa5ygXp0vIaIKpWcLncQD6h7+Nk9JEQOlb2jUv+XYwxRfKIb0pbuS7YmA5x9qWvSOygbrQDoqyL91Wtjm1VjsIVu/Dv+UGFkUcMUYzEbi/Vq//KIkzNhfKn1eheNab+G088BQ+Q0bOtLGYrb+fRvy/qtI3BeWZHVhe3ZjJaDwOxyFNZU1kk5FwNTi1adWflDhLIEs1rVbONzaUj5HqSmc0lhSzsS1WsZU=,iv:6JBf0rTDI6UxdA3zvTIa58P0xhCTrGi3Mp6xhXv2VzU=,tag:r4zqTkEJlAjGFnPJq26/YA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V2pqdHE2eFQvZ0x1RmRY
            QnE5amZjcGZieWJOU2VYbzd3NjNuWUJVcVc0CnNxTzVNeThDS052MCtQQzk2cE9z
            OXZ3UTlKVU41cTE0WXhIT3ZxVktuQVUKLS0tIEFDMnRKRmdneUp2blkwNkNOakpI
            YVJ3RDBUSy8ydlYzenlnSklDSG5FSEkKcW20fRVuVdfo7iRqFLUakpCfGjYpnV+r
            c739TvP7CUXdzSjaSIHP3KAx8OklhLyBy+qnMXLiU8bV9pWRXGneCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T12:06:29Z"
    mac: ENC[AES256_GCM,data:GaMt+d7M+Sicu2rbDc6dY1khIv1ZVz+cQbJnrOdFX2ANxD8EC7QZbY0VnhQDTqS0anIW5ak29ScD0FpeGa87aI/iyGAeG3m7VyNEPZ3Q5QLE54IL3auIEgwmKRAYYTc/DWnsObTjLJd0H+Ca62VNjHQoqGCPjoJxb+FwQANVU2o=,iv:50IoDIspDmGHZoCPrRObD9p1aKdpDxSPVkHgvTC9068=,tag:0FSnVerfmXnTpXUBeRQwKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
