apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden-config
  namespace: bitwarden
data:
  DOMAIN: "https://bitwarden.${SECRET_DOMAIN}"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_FROM: "alekss.ro.noreply@gmail.com"
  SMTP_PORT: "587"
  SMTP_SECURITY: "starttls"
  # Enable Vault interface, when disabled, only API is served
  WEB_VAULT_ENABLED: "true"
  SIGNUPS_ALLOWED: "true"
  INVITATIONS_ALLOWED: "true"
  # Number of workers to spin up for the service
  ROCKET_WORKERS: "10"
  # Port to serve http requests on
  # most likely no need to change this here, look at ingress configuration instead
  ROCKET_PORT: "8080"
