apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-data
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
