# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secrets
    namespace: bitwarden
stringData:
    SMTP_USERNAME: ENC[AES256_GCM,data:q09L9/l/dzoHO+/S964v,iv:Rv5F7c+gWi1xBHXPte01VGBBGRxWfTGYTP78zZSVHhY=,tag:0X74nXsV+WGChWY4dOw0QA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:78aXwCec+5/z1pw5LrnBFAGcNP5cmQ==,iv:Zrwgei3aIvsnOv5CMpl/EWsCzs2aI9VXFBG++KnfizI=,tag:7jcyCKf7TQ5vK19heZUC7g==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:ce8LdjPgYHblUzhuY2XCeyUkvtEklKjgT2+CsL4i9h6ydBrzZZN29uuwm5elfqA9+4rzcvGuu2eeB6KBSnHBcw==,iv:g0U74DVSv0MkPUEWHeFX4zIi2P+YyIOaPrEDEX7dLrc=,tag:tzwtF7Vy6wzdgcthKkODKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVRaUGNrSWIvL1ppVGNB
            ZFBraE1TUTdTRnBseWRtZzZzSmN6YkJvd0Y4Cm1xU0NyT0F6aVlhL3hYbWplcnNv
            VGU1WnJLTzhXSjhiWThaS2NVOGgrNXMKLS0tIGdRejFFL1dLNmNIRjlpRUZtYlRD
            SE0zMGgra01DYVVzOVk4T1Nac01FZUkKDHiTYn7QBsJy1RcykqjxrIF5mfb3dVMa
            W2+HsMzRQciLCqjsJnVAthxNREiFBfTu/mjvAqJ6zC0uxvggAp/TuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-04T12:28:06Z"
    mac: ENC[AES256_GCM,data:3oT0pcf9WV9tq2HeGYNLjyzFONetNfOgjFHjGB2vuKNcToVXRvKo2jsd/Led7TCmFmNFEWb5tAFfxpeLWNAfYg75WlKFoAplxgsFM2tC7ODuBaX7XZB1SgoQEiw44yaHVr7L5vgYn1kcSDkQHYiLyEvswdSxD2DTZW+oDIk5gbs=,iv:E1f4BByYpS6f7sLOhdnAlEmNPIjjBIAsx2c1IPDrYl8=,tag:9vkf8cj2AcuozIJ2m7tOiA==,type:str]
    version: 3.13.3
