# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secrets
    namespace: bitwarden
stringData:
    SMTP_USERNAME: ENC[AES256_GCM,data:zHgY9IErOCzlJSo3L6srRrih0WJH35ag,iv:EP+mUO0/utswSbxadQI4YzJKYcyo23CRX9YiOaVr7NY=,tag:0xJgVMwnyc4MjA4K22GcAQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:wtRtoFKiWb7PGQHeCqtghlHYQD3Q2Kfno9ghe684Ma1KxEZKdQKtXh9465/YYCoXBuAHIj2scqkqIWHu6PI9BSwOo+d4wwJC7t1jWLXjY3CzT8CSI9sulG0U,iv:v3QfFN1alj70ivZvicp76tV6ry7fStLszvB+y4W35qM=,tag:HKf/XSljOfGmu6RnrTQlGw==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:ce8LdjPgYHblUzhuY2XCeyUkvtEklKjgT2+CsL4i9h6ydBrzZZN29uuwm5elfqA9+4rzcvGuu2eeB6KBSnHBcw==,iv:g0U74DVSv0MkPUEWHeFX4zIi2P+YyIOaPrEDEX7dLrc=,tag:tzwtF7Vy6wzdgcthKkODKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRVRaUGNrSWIvL1ppVGNB
            ZFBraE1TUTdTRnBseWRtZzZzSmN6YkJvd0Y4Cm1xU0NyT0F6aVlhL3hYbWplcnNv
            VGU1WnJLTzhXSjhiWThaS2NVOGgrNXMKLS0tIGdRejFFL1dLNmNIRjlpRUZtYlRD
            SE0zMGgra01DYVVzOVk4T1Nac01FZUkKDHiTYn7QBsJy1RcykqjxrIF5mfb3dVMa
            W2+HsMzRQciLCqjsJnVAthxNREiFBfTu/mjvAqJ6zC0uxvggAp/TuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T23:53:26Z"
    mac: ENC[AES256_GCM,data:dWVD+hhJUexfz3yFykS9+TKXKwgRnT0/XzH+CgFKhDLawRjuhK1aeHY16dh01KkwPyUtz112sLMbNEAjlY6Ry4HNSFbNHBP5Bdkttb+v19hGgfpDqtD1JYSeCYJJlJ1m2puAxiM7RG5CkWof9sQ5UHcW01QNVp3wB8jo3M7QUQg=,iv:t3nqHCCfPhaM7TjkkfImhRTTzu3jmScVLMtuZbWUB3U=,tag:14kwlSprl5zupmlzJPCiAw==,type:str]
    version: 3.13.3
