apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: bitwarden
  labels:
    app: bitwarden
spec:
  serviceName: bitwarden
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      serviceAccountName: bitwarden
      securityContext:
        fsGroup: 33
        runAsUser: 33
      containers:
        - image: vaultwarden/server:1.25.2
          imagePullPolicy: IfNotPresent
          name: bitwarden
          envFrom:
            - configMapRef:
                name: bitwarden-config
          env:
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bitwarden-smtp
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitwarden-smtp
                  key: SMTP_PASSWORD
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 3012
              name: websocket
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: bitwarden-data
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 1Gi
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: bitwarden-data
          persistentVolumeClaim:
            claimName: bitwarden-data
