---
apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    service: bitwarden
spec:
  serviceName: bitwarden
  replicas: 1
  selector:
    matchLabels:
      service: bitwarden
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: bitwarden
    spec:
      serviceAccountName: bitwarden
      securityContext:
        fsGroup: 33
        runAsUser: 33
      containers:
        - image: vaultwarden/server:1.27.0
          imagePullPolicy: IfNotPresent
          name: bitwarden
          envFrom:
            - configMapRef:
                name: bitwarden-config
          env:
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: SMTP_PASSWORD
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: ADMIN_TOKEN
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 3012
              name: websocket
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: bitwarden-data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 256Mi
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: bitwarden-data
          persistentVolumeClaim:
            claimName: bitwarden-data
