kind: Secret
ansible_user: ENC[AES256_GCM,data:SgA/IsS66RzDVxU=,iv:eDSq96N2hdXWOPoouWp7x0P8waxbEFT4hIs0ABtQhho=,tag:HbOSuOZdPEaxwRjcg5zfIQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Dtuc9q7IJtZmpLoQMO2xArHGZCQ=,iv:Ic9+FfdhaC+hHuN75AiSsPttHohSPGW7Ea07643U3WM=,tag:l4EhrKXrIzqjY10Krn4IGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QUplOWRRQ3dxUG1VWlJj
            NFlRR1BzZEo1d0NhRlFRSk1QK2FsMC9GSkVzCm9hUGdYa3N5L0x3a3ptVFZIVWt0
            bnBiL0hzc2dVMVBVazdqTmt2THljMm8KLS0tIDFXeVdZa0NLTE1zSmhjVjc1ZytI
            ank5UXl5Z3dRcHdQUzVBUWp5NWsvUFUKs3cSX/U2yzvG/jq/Wqj37hcNjzC/Pu98
            JVNCBK0TZ2nZESZZKqLzwUvFaaT/llE9csRpXM4rec6TbNGf69Tcug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T02:30:42Z"
    mac: ENC[AES256_GCM,data:eErmri211LrKJey4K8XHCVawYwIkJa/NiQiJlh2u3Nl9BNq2wdyS4mwHdfTnpJUR6xMgB6U58eZyyFPgv15TcwYfnTKRIT1zaYxpFiFwK4T6PJxYTGWFZL/yxAZhcOZT3NsUaKQGoT/zxloGFigJc12e1r8e6QItLD5UrVgey+g=,iv:FUNw9ikg/tOMA/QCoZN8+kadWzRNEQB2PELqxR+5LGM=,tag:S2yEpXlgcvPtd0ngkyDJNw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
