apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-port-updater
  namespace: media-server
  annotations:
    # This cronjob updates the qbittorrent listen port from the Port Forwarded value provided by gluetun.
    reloader.stakater.com/auto: "true"
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: port-updater
              image: busybox
              env:
                - name: QBITTORRENT_USER
                  valueFrom:
                    secretKeyRef:
                      name: gluetun-conf
                      key: QBITTORRENT_USER
                - name: QBITTORRENT_PASS
                  valueFrom:
                    secretKeyRef:
                      name: gluetun-conf
                      key: QBITTORRENT_PASS
              command:
                - "/bin/sh"
                - "-c"
                - |
                  if [ ! -f /tmp/gluetun/forwarded_port ]; then
                    echo "forwarded_port file not found, exiting"
                    exit 0
                  fi
                  PORT=$(cat /tmp/gluetun/forwarded_port)
                  if [ -z "$PORT" ]; then
                    echo "Port is empty, exiting"
                    exit 0
                  fi
                  wget -O- --retry-connrefused -t 3 --save-cookies=cookies.txt --post-data "username=~$QBITTORRENT_USER~&password=~$QBITTORRENT_PASS~" http://127.0.0.1:8080/api/v2/auth/login
                  wget -O- --retry-connrefused -t 3 --load-cookies=cookies.txt --post-data "json={\"listen_port\":$PORT}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1
          restartPolicy: OnFailure
          volumes:
            - name: gluetun-tmp
              persistentVolumeClaim:
                claimName: gluetun-tmp-pvc
