apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-port-updater
  namespace: media-server
spec:
  # This cronjob updates the qbittorrent listen port from the Port Forwarded value provided by gluetun.
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: port-updater
              image: busybox
              env:
                - name: GLUETUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: media-secret
                      key: GLUETUN__AUTH__APIKEY
              command:
                - "/bin/sh"
                - "-c"
                - |
                  # Retrieve the forwarded port from Gluetun API using wget and sed
                  # JSON format: {"port":5914}
                  PORT=$(wget -qO- --header "X-API-Key: $GLUETUN_API_KEY" http://gluetun:8000/v1/portforward | sed -E 's/.*"port":([0-9]*).*/\1/')

                  if [ -z "$PORT" ]; then
                    echo "Failed to retrieve port from Gluetun, exiting"
                    exit 1
                  fi

                  echo "Retrieved port: $PORT"

                  # Update qBittorrent preferences
                  wget -qO- --post-data "json={\"listen_port\":$PORT}" http://qbittorrent:8080/api/v2/app/setPreferences
          restartPolicy: OnFailure
