apiVersion: batch/v1
kind: CronJob
metadata:
  name: qbittorrent-port-updater
  namespace: media-server
spec:
  # This cronjob updates the qbittorrent listen port from the Port Forwarded value provided by gluetun.
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: port-updater
              image: alpine
              command:
                - "/bin/sh"
                - "-c"
                - |
                  if [ ! -f /tmp/gluetun/forwarded_port ]; then
                    echo "forwarded_port file not found, exiting"
                    exit 0
                  fi
                  PORT=$(cat /tmp/gluetun/forwarded_port)
                  if [ -z "$PORT" ]; then
                    echo "Port is empty, exiting"
                    exit 0
                  fi
                  apk add --no-cache wget
                  wget -O- --retry-connrefused -t 3 --post-data "json={\"listen_port\":$PORT}" http://qbittorrent:8080/api/v2/app/setPreferences
              volumeMounts:
                - name: gluetun-tmp
                  mountPath: /tmp/gluetun
          restartPolicy: OnFailure
          volumes:
            - name: gluetun-tmp
              persistentVolumeClaim:
                claimName: gluetun-tmp-pvc
