# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dFl+FMfaeH4zBpGQ,iv:9va4SvKS484jQRpRFQLci+g9SszNgVwRVHCRkfxNiKg=,tag:dWMok2YcqBfk4N7mB4jjvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:gN1hRazHAKCotlOUrZjfJw==,iv:wG7Szzarl0e0wNmOtkZ2dYWUj6/0hn6+JM4ZS6hntDE=,tag:2ldtyvkSf+hrQyKL9taWeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZDhLbWJtRDlKUVZMcWg2
            ZEEyTWZBWVVCM2tsRUtwWmFiYjFsT2ErY0E0CnFFaEQxbGsyZEh6eG16Ukd0SHps
            M3VCaHRzVDB2L1BTYnBmeWZKRTRGYUEKLS0tIG9TNUJQQXdVa05OUlJFYUZXdHVh
            Vit6TGFpL0oyaTkwNmttdDN0SFBWNG8KtvT5zo9UbYp/X3cpTTISJIILLrbXiag+
            z1ZhovlonyTR/XlXPdd1YZMWukWEtd6FOkABc9EtLVvRIe59+Ha1hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T12:37:39Z"
    mac: ENC[AES256_GCM,data:17ooStx873MLYuRgpnd37hetqxpZ5aYFugJTK7SAtEIIE/S3/QOGAMoO2qQETCOQXwqQMnvh+QmRThOtps8k0DkuHTQtjiVfuMjTDKAY/F2RFeKUlOAPedwA/4dJavSqm7gIPZ0eI1+FDBT5hKn8jojzMFJu/X7OpupR6Jvl3uo=,iv:ofyXF2A+jHrqJp9oV8QXwb2+mRgbhhwxLd5hdjg3Q8Q=,tag:d6/WvmMkFOIKjp2VzvRg8g==,type:str]
    version: 3.13.3
