# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:dFl+FMfaeH4zBpGQ,iv:9va4SvKS484jQRpRFQLci+g9SszNgVwRVHCRkfxNiKg=,tag:dWMok2YcqBfk4N7mB4jjvQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OQOtVWUfW/HcGyh3zek4,iv:mL/AX15OtdlP0z2LiuUfvSDmL2BuhOyuwGfUZpfJm64=,tag:zQD7fIOQCW0br9AqdRnPNw==,type:str]
sops:
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZDhLbWJtRDlKUVZMcWg2
            ZEEyTWZBWVVCM2tsRUtwWmFiYjFsT2ErY0E0CnFFaEQxbGsyZEh6eG16Ukd0SHps
            M3VCaHRzVDB2L1BTYnBmeWZKRTRGYUEKLS0tIG9TNUJQQXdVa05OUlJFYUZXdHVh
            Vit6TGFpL0oyaTkwNmttdDN0SFBWNG8KtvT5zo9UbYp/X3cpTTISJIILLrbXiag+
            z1ZhovlonyTR/XlXPdd1YZMWukWEtd6FOkABc9EtLVvRIe59+Ha1hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T18:10:14Z"
    mac: ENC[AES256_GCM,data:Amci8Nm4/8ZyBo0duZ920if7aCSGIn6U8BUxcii0EzYUssS/rk55J0xA7IX8izTI9iNoXrztdQv65FlZjLKam4ogm+jDgFP0EnpullWFEcIcx377V/tK6TtOd2RvDXMJfffQpvOwD3PbRlFVYIv8dKwgzjMLclLrHaKmrrbE3bM=,iv:cTh3Jx7A/RJZ6gge90uO5HYfor3cjo3yq/WQR9FWlaE=,tag:8R8LRr+B42n41c57hdsgKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.3
