---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  namespace: media-server
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: seerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seerr
  template:
    metadata:
      labels:
        app: seerr
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /app/config && chmod -R 775 /app/config"]
          volumeMounts:
            - name: seerr-config
              mountPath: /app/config
      containers:
        - name: seerr
          image: ghcr.io/seerr-team/seerr:v3.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: media-config
          ports:
            - name: http
              containerPort: 5055
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: seerr-config
              mountPath: /app/config
      volumes:
        - name: seerr-config
          persistentVolumeClaim:
            claimName: jellyseerr-config-pvc
