apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanbn-db-data
  namespace: kanbn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
