apiVersion: v1
kind: Secret
metadata:
    name: kanbn-secret
    namespace: kanbn
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Oj1wP2IDWI4rD/sjuQCS,iv:Fo1E2nxKOSSwM2ytHrzCXuDsXlNS0WuaWvigISvVays=,tag:G8QlI2O4Fw+NAAlf8y9DAQ==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:edzGSdghaNt7ISJvXyiJXI+DOEa5SHG7gZ0xYDrNbKIRoYfJEpC4i6ImG5Og5Pj7pnNFsQ==,iv:YQA5WY8gFM2XOAWftq9IyTWqb4yiCdsClpToHYnbThQ=,tag:PsKEuZeDragwC0q3E2k6ow==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Dco1AM/aQrdAcdi4SiguAKDNmkbm9ur2klUp2vl5S4o=,iv:v1cIy5s4xOBOkTzcbJ7q+Pel4kR4/9g0ppneGGB3A98=,tag:UAB6XjbOLkgp8fa6D/YJoQ==,type:str]
sops:
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR2NWSU9YdGYvaE9OMmpP
            ZUg5WEpGV3hJSHBUZjdoWGx3TzE1RkpLUXhjCjlhYmFDUU9vd0hSbGRNZXhNc1Ir
            d1BnZGhOMzBZR1pRK0xPMng3ajF2Rm8KLS0tIEpVRmhBZ1o5T2IzL0ZOWjRPWk4r
            K0lZbWUrM1pNSFh1ZmgyUjNOT2JuVkEKeZxOdK522l29jyaeEDNB3M6P3t7/hIb7
            /vO02PM0aSymbGiLa3dimbt+nga9WIsXzf1szhMyAv0nnS3H21nJ3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T00:58:07Z"
    mac: ENC[AES256_GCM,data:AGJG2izGk46SFr+m/nWS/+9J3qNg4XWOHqqtwNXo4os5LdiLPHsCjUdTAWL/qT9cAruHR5Xl3Y4/E2YUx1OefRULEznEBjPAcE35+DhqfsxL/u1H0wCpIEqL4eXSCxcM1Pm6D4CmTf5fM+EGrk68mAGByxBHfM6ht4q2MJcxeVA=,iv:bWzACZF76PfREUEvc7UmOIwkXmtKK8036O7AJAa5hqg=,tag:b81RM3yFBc6Y2ukm4h0AuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
