---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.11.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    enablePSP: false
    replicaCount: 2
    defaultSettings:
      defaultReplicaCount: 2
      backupTarget: "s3://longhorn-backups@us-east-1/"
      backupTargetCredentialSecret: "longhorn-secret"
      nodeDownPodDeletionPolicy: "delete-both-statefulset-and-deployment-pod"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-internal-only@kubernetescrd"
      host: "longhorn.${SECRET_DOMAIN}"
      tls:
        - secretName: longhorn-tls
          hosts:
            - "longhorn.${SECRET_DOMAIN}"
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 256Mi
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
              name: longhorn-manager
            patch: |
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: longhorn-manager
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-manager
                        resources:
                          requests:
                            cpu: 50m
                            memory: 224Mi
                          limits:
                            memory: 224Mi
          - target:
              kind: DaemonSet
              name: longhorn-csi-plugin
            patch: |
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: longhorn-csi-plugin
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-csi-plugin
                        resources:
                          requests:
                            cpu: 50m
                            memory: 64Mi
                          limits:
                            memory: 64Mi
          - target:
              kind: Deployment
              name: longhorn-ui
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: longhorn-ui
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: longhorn-ui
                        resources:
                          requests:
                            cpu: 50m
                            memory: 64Mi
                          limits:
                            memory: 64Mi
          - target:
              kind: Deployment
              name: csi-attacher
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: csi-attacher
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: csi-attacher
                        resources:
                          requests:
                            cpu: 50m
                            memory: 64Mi
                          limits:
                            memory: 64Mi
          - target:
              kind: Deployment
              name: csi-provisioner
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: csi-provisioner
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: csi-provisioner
                        resources:
                          requests:
                            cpu: 50m
                            memory: 64Mi
                          limits:
                            memory: 64Mi
          - target:
              kind: Deployment
              name: csi-resizer
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: csi-resizer
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: csi-resizer
                        resources:
                          requests:
                            cpu: 50m
                            memory: 64Mi
                          limits:
                            memory: 64Mi
          - target:
              kind: Deployment
              name: csi-snapshotter
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: csi-snapshotter
                namespace: storage-system
              spec:
                template:
                  spec:
                    containers:
                      - name: csi-snapshotter
                        resources:
                          requests:
                            cpu: 50m
                            memory: 64Mi
                          limits:
                            memory: 64Mi
