---
apiVersion: v1
kind: LimitRange
metadata:
  name: storage-system-limits
  namespace: storage-system
spec:
  limits:
    - default:
        memory: 768Mi
      defaultRequest:
        cpu: 50m
        memory: 768Mi
      type: Container
