# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-secret
    namespace: storage-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:a/uoTEY=,iv:Pj9Oho06L74gR1+wPIrCyvsWvS2IhYUq1XwPHaK7aHc=,tag:vfEDV7zlIASDmGubFkUueQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ESnSp//0//GGfzet4A1twXO+Km0=,iv:uoOoiWv5sdwOASkJSZkvIlMO5OzAMjZwhbaedvKrD5w=,tag:xg4bQeOvYl34RfKuG2T0jg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:1Qn8n4Yi1s3wdJguuhnFAqqN0B+pobxhulo=,iv:mqbmCqvnSYMYz4k2rbFBc2k3g4IyOZfB7gKiTUDaB6o=,tag:M+fuWuR3vV827zqIrcilvQ==,type:str]
    CLOUDFLARE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:byePsSnrhoKiV8F+Rs9MKjuMwtauF0Yl4fI28LNBIZM=,iv:L/puWXsjtEVTy+v2E/YtzTjYrDbWqKEPllZkeGAyZgo=,tag:Qw98XyX59fEjdCPNYPdfaQ==,type:str]
    CLOUDFLARE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5hnNCiASgtEyEd27LawrrhWoSlhfd/BeVvCsVrxCzrZEfN/GPSwsSW9ahnjkpVpt/0B+5V9Dj14wiZBIcuq3Vg==,iv:xus2JSWMTguCsZiMyQmQ+tkyMH5okcaUImzM+OlTAdM=,tag:DF1YYrG+3w51NovuRyGdrw==,type:str]
    CLOUDFLARE_AWS_ENDPOINTS: ENC[AES256_GCM,data:OmOI6pUW6rSCx5uA30H3BbxzBjuUUYOU/hmvpSpg9PuO8MpfwPHrbJoAur59H47n7X2lEx9J4hoMT7heb9PyZFg=,iv:8c/BwmqHH1LSiPX9APWmByscXcfI4qTCiTgTciZJHa8=,tag:7doVDJbui0x3/BrYR9YUgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V2pqdHE2eFQvZ0x1RmRY
            QnE5amZjcGZieWJOU2VYbzd3NjNuWUJVcVc0CnNxTzVNeThDS052MCtQQzk2cE9z
            OXZ3UTlKVU41cTE0WXhIT3ZxVktuQVUKLS0tIEFDMnRKRmdneUp2blkwNkNOakpI
            YVJ3RDBUSy8ydlYzenlnSklDSG5FSEkKcW20fRVuVdfo7iRqFLUakpCfGjYpnV+r
            c739TvP7CUXdzSjaSIHP3KAx8OklhLyBy+qnMXLiU8bV9pWRXGneCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T11:58:03Z"
    mac: ENC[AES256_GCM,data:ZFOSP0ztWmK9J98ojgaCQAyijY0NKTVALFTiSke3ynXpqaONWZNIsUrKJw000af28eTWRDINP6TNa+IzOHLmUWhyO/9IlQdCxTChunvKGHl64CLHxKEzrCZM79fbGLG+3Rwca7DZQQZTnPSJ7QyTejwZa9s8SiOEfxcyT+aNhhc=,iv:NpmambW6Ib3ntqVC7zZjkI1rDs45P6+r8qObuZtoffk=,tag:cVbv3Hl2Qp3EPv/IU6KITg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
