---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge-data
  namespace: mail
  labels:
    app.kubernetes.io/name: protonmail-bridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
