---
apiVersion: v1
kind: Service
metadata:
  name: protonmail-bridge
  namespace: mail
  labels:
    app.kubernetes.io/name: protonmail-bridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: protonmail-bridge
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
    - name: smtp-submission
      port: 587
      targetPort: 25
      protocol: TCP
    - name: smtp-alt
      port: 1025
      targetPort: 25
      protocol: TCP
    - name: imap
      port: 143
      targetPort: 143
      protocol: TCP
