---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: protonmail-bridge
  namespace: mail
  labels:
    app.kubernetes.io/name: protonmail-bridge
spec:
  serviceName: protonmail-bridge
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: protonmail-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: protonmail-bridge
    spec:
      containers:
        - name: protonmail-bridge
          image: dancwilliams/protonmail-bridge:v3.26.0-4
          imagePullPolicy: IfNotPresent
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: imap
              containerPort: 143
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /root
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: protonmail-bridge-data
