apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media-server
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.15
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: media-config
          ports:
            - name: http
              containerPort: 8989
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              memory: "256Mi"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: media-data-pvc
