---
- name: Update max_user_watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: "65536"
    state: present
    sysctl_file: /etc/sysctl.d/98-kubernetes-fs.conf

- name: Disable swap at runtime
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swap on boot
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: Mount up HDD
  ansible.posix.mount:
    path: /srv/disk
    src: LABEL=SOME_LABEL
    fstype: ext4
    state: present
