---
- include_tasks: locale.yml
  tags:
    - locale

- include_tasks: packages.yml
  tags:
    - packages

- import_tasks: kernel.yml
  tags:
    - kernel

- include_tasks: network.yml
  tags:
    - network

- include_tasks: filesystem.yml
  tags:
    - filesystem

- include_tasks: unattended-upgrades.yml
  tags:
    - unattended-upgrades

- include_tasks: user.yml
  tags:
    - user
