apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: homeassistant
data:
  resolv.conf: |
    nameserver 192.168.1.121
    nameserver 8.8.8.8
  configuration.yaml: |
    default_config:
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    frontend:
      themes: !include_dir_merge_named themes
      extra_module_url:
        - /local/community/custom-brand-icons/custom-brand-icons.js
        - /hacsfiles/material-you-utilities/material-you-utilities.min.js

    panel_custom:
      - name: material-you-panel
        url_path: material-you-configuration
        sidebar_title: Material You Utilities
        sidebar_icon: mdi:material-design
        module_url: /hacsfiles/material-you-utilities/material-you-utilities.min.js

    http:
      ip_ban_enabled: false
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16 # cluster cidr
        - 192.168.1.0/24 # home assistant
        - 192.168.86.0/24 # google wifi
        #cloudflare ipv4
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        #cloudflare ipv6
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    google_assistant:
      project_id: homeassistant-88a71
      service_account: !include SERVICE_ACCOUNT.JSON
      report_state: true
