apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: homeassistant
data:
  resolv.conf: |
    nameserver 192.168.68.98
    nameserver 192.168.68.20
    nameserver 8.8.8.8
  configuration.yaml: |
    default_config:
    tts:
      - platform: google_translate

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml
    template: !include templates.yaml

    frontend:
      themes: !include_dir_merge_named themes
      extra_module_url:
        - /local/community/custom-brand-icons/custom-brand-icons.js
        - /hacsfiles/material-you-utilities/material-you-utilities.min.js

    panel_custom:
      - name: material-you-panel
        url_path: material-you-configuration
        sidebar_title: Material You Utilities
        sidebar_icon: mdi:material-design
        module_url: /hacsfiles/material-you-utilities/material-you-utilities.min.js

    http:
      ip_ban_enabled: false
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/16 # cluster cidr
        - 192.168.1.0/24 # main home network
        - 192.168.68.0/24 # deco mesh
        - 192.168.86.0/24 # google wifi
        #cloudflare ipv4
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        #cloudflare ipv6
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    google_assistant:
      project_id: homeassistant-88a71
      service_account: !include SERVICE_ACCOUNT.JSON
      report_state: true
  templates.yaml: |
    - sensor:
      - name: Grid Importacion
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power
        state: >
          {% if states('sensor.medidor_grid_power') | float >= 0 %}
            {{ states('sensor.medidor_grid_power') }}
          {% else %}
            0
          {% endif %}
      - name: Grid Exportacion
        unit_of_measurement: 'W'
        state_class: measurement
        device_class: power
        state: >
          {% if states('sensor.medidor_grid_power') | float < 0 %}
            {{ states('sensor.medidor_grid_power') | float * -1 }}
          {% else %}
            0
          {% endif %}
    - binary_sensor:
      - name: alekssro_home_wifi
        state: >-
          {% if states('sensor.pixel_9_pro_wi_fi_connection') == "R&A Home" %}
            on
          {% else %}
            off
          {% endif %}
      - name: raquel_home_wifi
        state: >-
          {% if states('sensor.pixel_7_wi_fi_connection') == "R&A Home" %}
            on
          {% else %}
            off
          {% endif %}
    - light:
      - name: "Luz Ventilador Habitación"
        unique_id: "luz_ventilador_habitacion"
        turn_on:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_habitacion
        turn_off:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_habitacion
      - name: "Luz Ventilador Porche Lado Cocina"
        unique_id: "luz_ventilador_porche_lado_cocina"
        turn_on:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_lado_cocina
        turn_off:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_lado_cocina
      - name: "Luz Ventilador Porche Lado Salón"
        unique_id: "luz_ventilador_porche_lado_salon"
        turn_on:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_lado_salon
        turn_off:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_lado_salon
      - name: "Luz Ventilador Salón"
        unique_id: "luz_ventilador_salon"
        turn_on:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_salon
        turn_off:
          - service: button.press
            target:
              entity_id: button.light_on_off_ventilador_salon
    - fan:
      - name: "Ventilador Habitación"
        unique_id: "ventilador_habitacion"
        state: "{{ not is_state('input_select.fan_speed_ventilador_habitacion', 'Off') }}"
        preset_mode: >
          {% if is_state('input_select.fan_speed_ventilador_habitacion', 'Off') %}
            None
          {% else %}
            {{ states('input_select.fan_speed_ventilador_habitacion') }}
          {% endif %}
        percentage: >
          {% set speed = states('input_select.fan_speed_ventilador_habitacion') %}
          {% if speed == 'Low' %}
            33
          {% elif speed == 'Medium' %}
            66
          {% elif speed == 'High' %}
            100
          {% else %}
            0
          {% endif %}
        turn_on:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_habitacion
          data:
            option: "Low" # Default speed when turned on
        turn_off:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_habitacion
          data:
            option: "Off"
        set_preset_mode:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_habitacion
          data:
            option: "{{ preset_mode }}"
        set_percentage:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_habitacion
          data:
            option: >
              {% if percentage == 0 %}
                Off
              {% elif percentage <= 33 %}
                Low
              {% elif percentage <= 66 %}
                Medium
              {% else %}
                High
              {% endif %}
        speed_count: 3
      - name: "Ventilador Porche Lado Cocina"
        unique_id: "ventilador_porche_lado_cocina"
        state: "{{ not is_state('input_select.fan_speed_ventilador_porche_lado_cocina', 'Off') }}"
        preset_mode: >
          {% if is_state('input_select.fan_speed_ventilador_porche_lado_cocina', 'Off') %}
            None
          {% else %}
            {{ states('input_select.fan_speed_ventilador_porche_lado_cocina') }}
          {% endif %}
        percentage: >
          {% set speed = states('input_select.fan_speed_ventilador_porche_lado_cocina') %}
          {% if speed == 'Low' %}
            33
          {% elif speed == 'Medium' %}
            66
          {% elif speed == 'High' %}
            100
          {% else %}
            0
          {% endif %}
        turn_on:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_cocina
          data:
            option: "Low"
        turn_off:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_cocina
          data:
            option: "Off"
        set_preset_mode:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_cocina
          data:
            option: "{{ preset_mode }}"
        set_percentage:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_cocina
          data:
            option: >
              {% if percentage == 0 %}
                Off
              {% elif percentage <= 33 %}
                Low
              {% elif percentage <= 66 %}
                Medium
              {% else %}
                High
              {% endif %}
        speed_count: 3
      - name: "Ventilador Porche Lado Salón"
        unique_id: "ventilador_porche_lado_salon"
        state: "{{ not is_state('input_select.fan_speed_ventilador_porche_lado_salon', 'Off') }}"
        preset_mode: >
          {% if is_state('input_select.fan_speed_ventilador_porche_lado_salon', 'Off') %}
            None
          {% else %}
            {{ states('input_select.fan_speed_ventilador_porche_lado_salon') }}
          {% endif %}
        percentage: >
          {% set speed = states('input_select.fan_speed_ventilador_porche_lado_salon') %}
          {% if speed == 'Low' %}
            33
          {% elif speed == 'Medium' %}
            66
          {% elif speed == 'High' %}
            100
          {% else %}
            0
          {% endif %}
        turn_on:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_salon
          data:
            option: "Low"
        turn_off:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_salon
          data:
            option: "Off"
        set_preset_mode:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_salon
          data:
            option: "{{ preset_mode }}"
        set_percentage:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_porche_lado_salon
          data:
            option: >
              {% if percentage == 0 %}
                Off
              {% elif percentage <= 33 %}
                Low
              {% elif percentage <= 66 %}
                Medium
              {% else %}
                High
              {% endif %}
        speed_count: 3
      - name: "Ventilador Salón"
        unique_id: "ventilador_salon"
        state: "{{ not is_state('input_select.fan_speed_ventilador_salon', 'Off') }}"
        percentage: >
          {% set speed = states('input_select.fan_speed_ventilador_salon') %}
          {% if speed == '1' %}
            20
          {% elif speed == '2' %}
            40
          {% elif speed == '3' %}
            60
          {% elif speed == '4' %}
            80
          {% elif speed == '5' %}
            100
          {% else %}
            0
          {% endif %}
        preset_mode: >
          {% if is_state('input_select.fan_speed_ventilador_salon', 'Off') %}
            None
          {% else %}
            {{ states('input_select.fan_speed_ventilador_salon') }}
          {% endif %}
        direction: "{{ states('input_select.fan_direction_ventilador_salon') }}"
        turn_on:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_salon
          data:
            option: "2" # Default speed when turned on
        turn_off:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_salon
          data:
            option: "Off"
        set_percentage:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_salon
          data:
            option: >
              {% set p = percentage | int %}
              {% if p == 0 %}
                Off
              {% elif p <= 20 %}
                1
              {% elif p <= 40 %}
                2
              {% elif p <= 60 %}
                3
              {% elif p <= 80 %}
                4
              {% else %}
                5
              {% endif %}
        set_preset_mode:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_speed_ventilador_salon
          data:
            option: "{{ preset_mode }}" # preset_mode will be "1", "2", "3", "4", or "5"
        set_direction:
          service: input_select.select_option
          target:
            entity_id: input_select.fan_direction_ventilador_salon
          data:
            option: "{{ direction }}" # direction will be "forward" or "reverse"
        speed_count: 5
    - cover:
      - name: "Puerta Garaje"
        device_class: garage
        unique_id: puerta_corredera_garaje
        state: >
          {% if is_state('binary_sensor.sensor_puerta_corredera_garaje', 'on') %}
            open
          {% elif is_state('binary_sensor.sensor_puerta_corredera_garaje', 'off') %}
            closed
          {% else %}
            closed {# Default to 'closed' if the sensor state is unknown or unavailable #}
          {% endif %}
        open_cover:
          service: switch.toggle
          target:
            entity_id: switch.puerta_garaje
        close_cover:
          service: switch.toggle
          target:
            entity_id: switch.puerta_garaje
        stop_cover:
          service: switch.toggle
          target:
            entity_id: switch.puerta_garaje
        position: >
          {% if is_state('binary_sensor.sensor_puerta_corredera_garaje', 'on') %}
            100
          {% elif is_state('binary_sensor.sensor_puerta_corredera_garaje', 'off') %}
            0
          {% else %}
            {{ state_attr(this.entity_id, 'current_position') | default(0) }}
          {% endif %}
        icon: >
          {% if is_state('binary_sensor.sensor_puerta_corredera_garaje', 'on') %}
            mdi:garage-open-variant
          {% elif is_state_attr(this.entity_id, 'current_position', 0) or is_state('binary_sensor.sensor_puerta_corredera_garaje', 'off') %}
            mdi:garage-variant
          {% else %}
            mdi:garage-alert-variant
          {% endif %}
