apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: homeassistant
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns/is-public: "true"
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "home-assistant.${SECRET_DOMAIN}"
      secretName: homeassistant-tls
  rules:
    - host: "home-assistant.${SECRET_DOMAIN}"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: homeassistant
                port:
                  number: 8123

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: homeassistant-music-assistant
#   namespace: homeassistant
#   annotations:
#     cert-manager.io/cluster-issuer: "letsencrypt-production"
#     external-dns/is-public: "true"
#     external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
#     traefik.ingress.kubernetes.io/router.middlewares: "networking-cloudflare-only@kubernetescrd"
# spec:
#   ingressClassName: traefik
#   tls:
#     - hosts:
#         - "music-assistant.${SECRET_DOMAIN}"
#       secretName: homeassistant-music-assistant-tls
#   rules:
#     - host: "music-assistant.${SECRET_DOMAIN}"
#       http:
#         paths:
#           - pathType: Prefix
#             path: /
#             backend:
#               service:
#                 name: homeassistant-music-assistant
#                 port:
#                   number: 8095
