---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: homeassistant
data:
  mosquitto.conf: |
    # Listen on port 1883 on all IPv4 interfaces
    listener 1883
    socket_domain ipv4

    # save the in-memory database to disk
    persistence true
    persistence_location /mosquitto/data/

    # Log to stderr and logfile
    log_dest stderr

    # Require authentication
    allow_anonymous false
    password_file /mosquitto/config/mosquitto.passwd
