apiVersion: v1
kind: ConfigMap
metadata:
  name: nut-upsd-config
  namespace: homeassistant
data:
  ups.conf: |
    [ups]
        driver = blazer_usb
        port = auto
        vendorid = 0665
        productid = 5161
        user = root
        pollinterval = 5
        desc = "Server - Salicru SPS 1500 ONE V2"
