apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media-server
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      initContainers:
        - name: volume-permission-fixes
          image: busybox:latest
          command: ["sh", "-c", "chown -R 1000:1000 /config /data"]
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: data
              mountPath: /data
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.27.5
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: media-config
          ports:
            - name: http
              containerPort: 7878
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: data
          persistentVolumeClaim:
            claimName: media-data-pvc
