---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-sync-pvc
  namespace: syncthing
  labels:
    app: obsidian-sync
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
