---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: insights-agent
  namespace: insights-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: fairwinds
      version: 2.10
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    insights:
      organization: "${insights-org}"
      cluster: "${insights-cluster}"
      base64token: "${insights-base64token}"
    goldilocks:
      enabled: true
    polaris:
      enabled: true
