---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: insights-agent
  namespace: insights-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: insights-agent
      version: 2.15.1
      sourceRef:
        kind: HelmRepository
        name: insights-agent
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: insights-agent-secrets
      valuesKey: values.yaml
      optional: false
