# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: insights-agent-secret
    namespace: insights-agent
stringData:
    ORGANIZATION: ENC[AES256_GCM,data:aTDjdq15CaY=,iv:7BxK1ROvB8uXLWJ8uUIc92aCBJrnLeQPEAvy6RZMuwY=,tag:9Kao8HZQCypOYUe4SiWBqA==,type:str]
    CLUSTER: ENC[AES256_GCM,data:RSE5KU+IDdE=,iv:aY9fhZNqTywDZc8AdsBziKECAKaHoFsGXU0hNALt6dQ=,tag:ts+xi8JaGV0zC8ok58Fk1w==,type:str]
    BASE64TOKEN: ENC[AES256_GCM,data:friZeQjTFR7hW8wjLF++h7y0FPC8wskGgH/PHVwlbbOxyWJXUXFQaWaLJ4WshxquJR07BhFpwO+oaiecsKM49/PyaVAtQ0CsLrWT49PBAoq5RBVuFBK/Ug==,iv:Hj7mFC9om2DAAzkTfM0m2ZvjicbikIcILm+xw3X4Vt0=,tag:e3Q6gH0r3Bl3UtveCEHxXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V2pqdHE2eFQvZ0x1RmRY
            QnE5amZjcGZieWJOU2VYbzd3NjNuWUJVcVc0CnNxTzVNeThDS052MCtQQzk2cE9z
            OXZ3UTlKVU41cTE0WXhIT3ZxVktuQVUKLS0tIEFDMnRKRmdneUp2blkwNkNOakpI
            YVJ3RDBUSy8ydlYzenlnSklDSG5FSEkKcW20fRVuVdfo7iRqFLUakpCfGjYpnV+r
            c739TvP7CUXdzSjaSIHP3KAx8OklhLyBy+qnMXLiU8bV9pWRXGneCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T21:40:47Z"
    mac: ENC[AES256_GCM,data:iUVvxhgTrzni2PzFZecSVT5K40wtT3KQ14qH3jNp8GhzcCpZ/7XsZiIkTl2twZmhFtkUE+qa3hms+5DiyHSU/yC5tlNSLxMu+2qHIvxm2+QqjZJoxEkXgpPxuxKdtOArEX/3z6zwEYQ5L6g+FTqbmtpBZyi0QiKYybvyTI7X3Mo=,iv:xwDcj92yr4w91furp2WKeu82KTOMgcojpm8WuBmaIN0=,tag:Ye7iiW9tMg+SYXSZeYOeJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
