# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: insights-agent-secrets
    namespace: insights-agent
stringData:
    values.yaml: ENC[AES256_GCM,data:B5Fcc9pvW1ACsbpBnUjIrUhIh0rLzGNBJ9P9JA4waOPBmQm1pqYen3qVk+lWlQHQkkwtYegieK/OCOshIEBmi06iJPuShlh9D+Ksjk8Ud/mKLj2SfpzSke7q/d6lB1KOwRdFXVhSPZYzIB4W+HopMnkasgZzU965gCZmd//xR6dPq04ykhUbUQLLAgIrHJVk3eUyxn0r3wL4NDoEu7ExaWwdwR/vpOg9nzrCcWu1UXvS2c+hGOsCg6BVU1Fwoo7lqmNRBbi1tVROQFG8t/Cq0DdYaYoloItwaqZf7hOr/xcA7nx/,iv:4qQgORr1ZNvU+j5+fbWhDv/OjrkBOpamSoTvMXt8+dA=,tag:JRI2lLhbnRMh7n3fcbvISQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lmvps8d0k8y4dx5wke4r2nqrhr4gvhu2wtpmlm8dsvtyj36kk5rsd7eefp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V2pqdHE2eFQvZ0x1RmRY
            QnE5amZjcGZieWJOU2VYbzd3NjNuWUJVcVc0CnNxTzVNeThDS052MCtQQzk2cE9z
            OXZ3UTlKVU41cTE0WXhIT3ZxVktuQVUKLS0tIEFDMnRKRmdneUp2blkwNkNOakpI
            YVJ3RDBUSy8ydlYzenlnSklDSG5FSEkKcW20fRVuVdfo7iRqFLUakpCfGjYpnV+r
            c739TvP7CUXdzSjaSIHP3KAx8OklhLyBy+qnMXLiU8bV9pWRXGneCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T21:45:36Z"
    mac: ENC[AES256_GCM,data:HXAoeYU2cVIbQSbRTsJD+VNVwnu502JNCcK/tL4YNeQ4zG4fmyVImryKVakRRVqWVGHvwG+fVXGUEY08QsR7gnMr3mzmNx7ZYhb7PPrGKJi/9Ap333ZTxPwGaqFRwVG4gU1V6H45nYKVco2nYupwRC7Agp0D/qaacIFl6M7H4E4=,iv:brVmNUcIjwjQiuyckDUHKMC2na3B/rpZ2Z/qoxF81fg=,tag:lMjsaPjTIntLSfzZuGf5CQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
