---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: 6.1.47
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 50m
        memory: 192Mi
      limits:
        memory: 192Mi
    configuration:
      logging:
        minimumLevel: Debug
